### ISSUE TITLE
MVP List Checklist

### ISSUE THREAD

**Issue by siascone** [mataghva/Footprint#2]
# MVP List
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
## Comments

**Comment by siascone** [comment]
- Missing formatting (use headers for MVPs) reference bluebird
- Missing completion dates and estimations
- Missing description sentence of app
- The 4 Features should be named and ordered Trails, Parks, Reviews, Search
- Missing deletion options for reviews

**Comment by siascone** [comment]
Looks Great!
