### ISSUE TITLE
Backend Routes Checklist

### ISSUE THREAD

**Issue by siascone** [mataghva/Footprint#5]
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments

**Comment by siascone** [comment]
Looks great! 
- Something to think about, do you want a route to return information of all parks or just individual parks?

**Comment by mataghva** [comment]
Thank you for checking that.
As I checked the original website, it seems there is not so much informtion about each park, thats why our table for parks is small in compare to trials. I think the parks are just needed to show all trails located in each park. So probably we don't need to list all parks at the same time. We need to search parks by name and then use filters to show the trails inside them.
Please let me know if you think I have to make it possible to list all parks.
